title: Rajiv Menon # your name (or website title) here
logo: "/images/Rajiv-1.png?raw=true" # your photo (or logo) here
description: 

Research Scientist with 4+ years of experience in Medical Imaging Research, 
Machine Learning and Data Science. 
  <br><br>
<a href="https://www.linkedin.com/in/rajivmenong">View My LinkedIn Profile</a> 


remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-3X5FH8Q3WY # your Google Analytics tracking ID here
